### ISSUE TITLE
flip display of video. 映像の回転。

### ISSUE THREAD

**Issue by teletubbiesarenotforpendingpandas** [t-asano/tinyviewplus#17]
please can you add the posibility to change or flip the video?

flip video 90º
flip video 180º

sometimes not everyone installs there fpv in the right upward position.

so far i can get it to work using this technique in osx:https://support.displaylink.com/knowledgebase/articles/589248-screen-rotation-option-is-not-available-on-mac-os

but its a very bad way to do it.

thanks for the .app

**Comment by t-asano** [comment]
180° will be easy.

90° will be difficult, if you want to keep aspect ratio (width:height=3:4). Changing ratio to 4:3 (stretch horizontal or trim vertical) will be easy.

**Comment by teletubbiesarenotforpendingpandas** [comment]
well for me 180º would be good enough for the moment.
thanks

**Comment by t-asano** [comment]
I will try.

**Comment by t-asano** [comment]
By the way, are they not troubled when using goggles?

**Comment by teletubbiesarenotforpendingpandas** [comment]
hello im just wondering if you managed to add flip 180º?

**Comment by t-asano** [comment]
I have not started yet because the priority of this problem is low. Are there many people installing the camera in the opposite direction?

**Comment by t-asano** [comment]
Please use code snippet below.
It's difficult to implement as a standard function.

//--------------------------------------------------------------
void drawCameraImage(int camidx) {
    int i = camidx;
    ofSetColor(myColorWhite);
#if true
    /* xxx rotate 180 */
    ofImage img;
    img.setFromPixels(grabber[i].getPixels().getData(),
                      grabber[i].getWidth(), grabber[i].getHeight(), OF_IMAGE_COLOR);
    img.rotate90(2);
    img.draw(camView[i].posX, camView[i].posY, camView[i].width, camView[i].height);
#else
    grabber[i].draw(camView[i].posX, camView[i].posY, camView[i].width, camView[i].height);
#endif
}
