### ISSUE TITLE
In 0.9.29 Race Result show TotalTime always equal Race Duration for all pilots

### ISSUE THREAD

**Issue by mchelifpv** [t-asano/tinyviewplus#23]
In 0.9.29 version Result page show TotalTime always equal Race Duration for all pilots, if Race Duration is set. Set wait after time limit on or off - same. If set Race Duration No limit, TotalTime show correctly.

**Comment by t-asano** [comment]
Thank you. I will fix it.

**Comment by t-asano** [comment]
This commit will fix issue. Please check it.
https://github.com/t-asano/tinyviewplus/commit/f4ed059bbbf329be89d818b8df889dc94b88ea80

**Comment by mchelifpv** [comment]
Tested. All ok.

**Comment by t-asano** [comment]
Thank you!!
