### ISSUE TITLE
macOS - damaged app error

### ISSUE THREAD

**Issue by JimB40** [t-asano/tinyviewplus#27]
<img width="441" alt="Screenshot 2020-04-16 at 17 06 56" src="https://user-images.githubusercontent.com/46420768/79473048-e0534700-8004-11ea-9b04-0189887d5c77.png">

Version 0.9.27 is the last I can run on macOS (10.15.2 Catalina)
Every higher version throws error that app is damaged.

**Comment by t-asano** [comment]
![EED3BFEA-F621-452B-B392-A40D66705A8D](https://user-images.githubusercontent.com/14119184/79481483-883f3380-804a-11ea-8287-ca1e95745ec3.jpeg)
Please try xattr command.

**Comment by JimB40** [comment]
Sorry haven't noticed change in manual. Worked thx.
