### ISSUE TITLE
Doesn't seem to work on M1 Macs

### ISSUE THREAD

**Issue by ZillionPrey** [t-asano/tinyviewplus#29]
Hi, I wanted to try the TinyViewPlus Software.

Sadly, it doesn't work as expected. It detects my two receivers but there is no video. Just weird artifacts.

![image](https://user-images.githubusercontent.com/6315513/142711163-f245831f-eec0-4daa-9a68-a10bf0c7072d.png)

**Comment by t-asano** [comment]
I just got a M1 Mac. I will check it out.

**Comment by t-asano** [comment]
@DerpyDoom
Tiny View Plus v0.9.31 works on M1 Macs.
I checked with MacBook Air (M1, 2020), macOS Monterey 12.0.1, Rosetta 2.
Please check security & privacy settings for camera.

<img width="1440" alt="Screen Shot 2021-12-04 at 5 13 23" src="https://user-images.githubusercontent.com/14119184/144667328-6b0c5ea1-61ab-4e70-be8f-f302fae1f199.png">

<img width="668" alt="Screen Shot 2021-12-04 at 5 12 22" src="https://user-images.githubusercontent.com/14119184/144669159-2dceef4d-7f30-43aa-beb9-e01998adae89.png">
